### ISSUE TITLE
4/20/17 ToDo List

### ISSUE THREAD

**Issue by SamMorrison7** [TheDragonCoder/cgt-system#1]
# These are the important things for our website.

- [x] No orange background
- [ ] Condense GIS and Drone page
- [ ] Screenshots as buttons. on hover, it will explain what the page is
- [ ] Add a video on the bottom (Wait on Trey)
- [ ] Buttons are vertical line 
- [ ] Replace heading with CGT logo and remove ecotek logo
- [ ] When you hover over a photo, information will appear on a present table
- [ ] Make the photos expand when hovered over, then it will contract when left.
- [ ] Make it a navbar so that you don't have to always go home

**Comment by SamMorrison7** [comment]
# Sam's Tasks

- [ ] Improve the quality of the buttons (DO NOT REMOVE CLASS FADE)
- [ ] Placement/Layout on the Drone/GIS page. Need photos, chart, and maps thing
- [ ]
