### ISSUE TITLE
4/20/17 Sam's ToDo

### ISSUE THREAD

**Issue by TheDragonCoder** [TheDragonCoder/cgt-system#2]
- [ ] Improve the quality of the buttons
- [ ] Change the layout of GIS/Drone Page (Needs a chart, photos, and map)
- [ ] Here, for a test, change the color of the orange background to a white color. The stylesheets are in the public folder, under house.css. Check this when you're done.

**Comment by TheDragonCoder** [comment]
Sam, make sure to do the last box to test that everything works properly
